CC = gcc
CFLAGS = -Wall -pthread

all: sum_serial sum_multi-thread

sum_serial: sum_serial.c
	$(CC) $(CFLAGS) -o sum_serial sum_serial.c

sum_multi-thread: sum_multi-thread.c
	$(CC) $(CFLAGS) -o sum_multi-thread sum_multi-thread.c

clean:
	rm -f sum_serial sum_multi-thread
